# Generated by Django 4.1.1 on 2022-09-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_detail_delete_detial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='section',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='teacher',
        ),
    ]
