# Generated by Django 4.1.1 on 2022-09-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_remove_detail_section_remove_detail_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='section',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='semester',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
