# Generated by Django 4.1.1 on 2022-09-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0005_quotas"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotas",
            name="days",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
