# Generated by Django 4.1.1 on 2022-09-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0006_quotas_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotas",
            name="time",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
