# Generated by Django 4.1.1 on 2022-09-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0007_quotas_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotas",
            name="details",
        ),
        migrations.AddField(
            model_name="quotas",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="qouta", to="subject.detail"
            ),
        ),
    ]
