# Generated by Django 4.1.1 on 2022-09-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0008_remove_quotas_details_quotas_subjects"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quotas",
            old_name="subjects",
            new_name="open",
        ),
    ]
