# Generated by Django 4.1.1 on 2022-09-16 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0009_rename_subjects_quotas_open"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotas",
            name="open",
        ),
        migrations.AddField(
            model_name="quotas",
            name="open",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotas",
                to="subject.detail",
            ),
        ),
    ]
