# Generated by Django 4.1.1 on 2022-09-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0010_remove_quotas_open_quotas_open"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quotas",
            old_name="open",
            new_name="subject",
        ),
    ]
