# Generated by Django 4.1.1 on 2022-09-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subject", "0011_rename_open_quotas_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_quotas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.ManyToManyField(
                        blank=True, related_name="user_quota", to="subject.quotas"
                    ),
                ),
            ],
        ),
    ]
