# Generated by Django 4.1.1 on 2022-09-16 15:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0003_alter_user_quotas_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_quotas",
            name="user",
            field=models.ForeignKey(
                default=django.contrib.auth.models.User,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usequota",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
