# Generated by Django 4.1.1 on 2022-09-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_quotas_amount_taken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_quotas",
            name="amount_taken",
            field=models.IntegerField(default=1),
        ),
    ]
