name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install -r AS2/requirements.txt
        python AS2/manage.py makemigrations
        python AS2/manage.py migrate
        coverage run --source='.' AS2/manage.py test
        coverage report
